"""
common/streams_client.py

Redis Streams-based message transport replacing Kafka.

This file is the CORE abstraction layer for your messaging system.

It replaces Kafka with Redis Streams while keeping the same concepts:
- Producer → publish()
- Consumer → read_many()
- Acknowledgement → ack()
- Recovery → claim_orphans()

========================================================
KEY REDIS STREAM CONCEPTS (VERY IMPORTANT)
========================================================

1. STREAM
   A stream is like a log (similar to a Kafka topic).
   Example:
       stock.events
       payment.commands

2. MESSAGE
   Each message has:
       - ID (generated by Redis, e.g. 1678901234-0)
       - Fields (we store everything under key 'd' as msgpack)

3. CONSUMER GROUP
   Multiple workers share a group:
       - each message is delivered to ONE consumer
       - enables load balancing

4. PENDING ENTRIES LIST (PEL)
   When a consumer reads a message:
       → it goes into PEL
       → it stays there UNTIL ACKED

   This is CRITICAL:
       - prevents message loss
       - enables crash recovery

5. ACK (XACK)
   Marks message as processed → removes it from PEL

6. ORPHANS
   Messages that:
       - were read
       - but NOT acked
       - because consumer crashed

   These must be reclaimed (XAUTOCLAIM)

========================================================
WHY THIS EXISTS
========================================================

Your system uses:
- event-driven architecture
- saga / 2PC coordination

So you need:
- reliable message delivery
- fault tolerance
- recovery after crashes

This wrapper provides ALL of that.
"""

from typing import List, Tuple
import redis as redis_module
from msgspec import msgpack


# Max length of each stream (approximate trimming)
# Prevents unbounded memory growth
STREAM_MAXLEN = 100_000

# How long XREADGROUP blocks waiting for messages (ms)
CONSUMER_BLOCK_MS = 500

# Number of messages to read per batch
DEFAULT_READ_COUNT = 32


class StreamsClient:
    """
    Thin wrapper over Redis Streams.

    This class is used by ALL services to:
        - publish messages (like Kafka producer)
        - consume messages (like Kafka consumer)
        - ack messages
        - recover orphaned messages

    Each service creates its own StreamsClient with its Redis connection.
    """

    def __init__(self, db: redis_module.Redis):
        """
        db = Redis connection (can point to any Redis instance)

        Example:
            stock_sc = StreamsClient(stock_redis)
        """
        self._db = db

    # =========================================================
    # GROUP MANAGEMENT
    # =========================================================

    def ensure_group(self, stream: str, group: str) -> None:
        """
        Ensure a consumer group exists for a stream.

        Redis requires groups to exist BEFORE consuming.

        - mkstream=True → creates stream if it doesn't exist
        - id='0' → group will see ALL messages from beginning

        Used during service startup.

        Example:
            stock.events + order-service group

        If group already exists:
            Redis throws BUSYGROUP → we ignore it
        """
        try:
            self._db.xgroup_create(stream, group, id='0', mkstream=True)
        except redis_module.exceptions.ResponseError as exc:
            if 'BUSYGROUP' not in str(exc):
                raise

    # =========================================================
    # PRODUCER (PUBLISH)
    # =========================================================

    def publish(self, stream: str, message: dict) -> None:
        """
        Publish a message to a stream (equivalent to Kafka produce).

        Internally uses:
            XADD

        We encode message using msgpack for efficiency.

        maxlen:
            prevents stream from growing infinitely

        approximate=True:
            faster trimming (not exact size)

        Example usage:
            publish("stock.commands", {...})

        In your system:
            Order service publishes commands
            Stock/Payment services publish events
        """
        self._db.xadd(
            stream,
            {'d': msgpack.encode(message)},
            maxlen=STREAM_MAXLEN,
            approximate=True,
        )

    # =========================================================
    # CONSUMER (READ)
    # =========================================================

    def read_many(
        self,
        streams: List[str],
        group: str,
        consumer: str,
        block_ms: int = CONSUMER_BLOCK_MS,
        pending: bool = False,
        count: int = DEFAULT_READ_COUNT,
    ) -> List[Tuple[str, bytes, dict]]:
        """
        Read messages from one or more streams.

        Uses:
            XREADGROUP

        PARAMETERS:
        --------------------------------------------------------
        streams:
            list of streams to read from

        group:
            consumer group name

        consumer:
            unique worker name

        pending:
            False → read NEW messages (">")
            True  → read PENDING messages ("0")

        count:
            batch size

        block_ms:
            how long to wait for new messages

        --------------------------------------------------------
        RETURN:
            [(stream_name, msg_id, message_dict), ...]

        --------------------------------------------------------
        IMPORTANT BEHAVIOR:

        pending=False:
            → reads NEW messages
            → blocks until messages arrive

        pending=True:
            → reads from PEL (unacked messages)
            → does NOT block

        --------------------------------------------------------
        USED FOR:

        1. Normal processing:
            pending=False

        2. Recovery after crash:
            pending=True
        """

        # '>' means only new messages
        # '0' means read from PEL
        start = '0' if pending else '>'

        # Only block for new messages
        block_arg = None if pending else block_ms

        result = self._db.xreadgroup(
            groupname=group,
            consumername=consumer,
            streams={s: start for s in streams},
            count=count,
            block=block_arg,
        )

        if not result:
            return []

        decoded = []

        # Decode Redis response into usable format
        for stream_raw, msgs in result:
            sname = stream_raw.decode() if isinstance(stream_raw, bytes) else stream_raw

            for msg_id, fields in msgs:
                raw = fields.get(b'd') or fields.get('d')

                decoded.append(
                    (sname, msg_id, msgpack.decode(raw))
                )

        return decoded

    def read_one(
        self,
        streams: List[str],
        group: str,
        consumer: str,
        block_ms: int = CONSUMER_BLOCK_MS,
        pending: bool = False,
    ) -> Tuple[str, bytes, dict] | None:
        """
        Convenience wrapper for reading ONE message.

        Internally calls read_many(count=1).

        Used when:
            - you want simple sequential processing
        """
        batch = self.read_many(
            streams=streams,
            group=group,
            consumer=consumer,
            block_ms=block_ms,
            pending=pending,
            count=1,
        )
        return batch[0] if batch else None

    # =========================================================
    # ACKNOWLEDGEMENT (CRITICAL)
    # =========================================================

    def ack(self, stream: str, group: str, msg_id) -> None:
        """
        ACK = mark message as processed.

        Internally:
            XACK

        Removes message from PEL.

        If you DON'T ACK:
            → message stays pending
            → will be retried later

        Used AFTER successful processing.
        """
        self._db.xack(stream, group, msg_id)

    def ack_many(self, stream: str, group: str, msg_ids: List[bytes]) -> None:
        """
        Batch ACK multiple messages.

        More efficient (1 network call instead of many).

        Used in your worker after processing a batch.
        """
        if msg_ids:
            self._db.xack(stream, group, *msg_ids)

    # =========================================================
    # FAILURE RECOVERY (VERY IMPORTANT)
    # =========================================================

    def claim_orphans(
        self,
        streams: List[str],
        group: str,
        consumer: str,
        min_idle_ms: int = 30_000,
    ) -> List[Tuple[str, bytes, dict]]:
        """
        Recover messages from crashed consumers.

        Uses:
            XAUTOCLAIM

        --------------------------------------------------------
        WHAT IS AN ORPHAN?

        A message is an "orphan" if:
            - it was read by a consumer
            - but NEVER ACKED
            - because the consumer crashed

        These messages sit in the PEL forever unless reclaimed.

        --------------------------------------------------------
        WHAT THIS FUNCTION DOES:

        - Finds messages idle for > min_idle_ms
        - Transfers them to THIS consumer
        - Returns them for reprocessing

        --------------------------------------------------------
        WHY THIS IS CRITICAL:

        Without this:
            → messages are LOST FOREVER

        With this:
            → system becomes fault-tolerant

        --------------------------------------------------------
        USED BY:

        Your:
            _orphan_recovery_worker()

        --------------------------------------------------------
        Equivalent in Kafka:
            - consumer group rebalance
            - offset reassignment
        """

        recovered = []

        for stream in streams:
            try:
                # XAUTOCLAIM:
                # - finds idle messages
                # - assigns them to this consumer
                _, msgs, _ = self._db.xautoclaim(
                    stream,
                    group,
                    consumer,
                    min_idle_time=min_idle_ms,
                    start_id='0-0',
                    count=100,
                )

                for msg_id, fields in msgs:
                    raw = fields.get(b'd') or fields.get('d')

                    recovered.append(
                        (stream, msg_id, msgpack.decode(raw))
                    )

            except Exception:
                # Fail silently to avoid crashing recovery loop
                pass

        return recovered